version: "3.9"

services:
  reporting-service:
    container_name: reporting-service
    build: .
    ports:
      - "4005:4005"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
