version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: reporting-postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    environment:
      POSTGRES_USER: reports_admin
      POSTGRES_PASSWORD: Letme1nplz!
      POSTGRES_DB: reporting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reporting-net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - reporting-net

volumes:
  postgres_data:

networks:
  reporting-net:
